name: observa_gye_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  back_button_interceptor: ^8.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  http: ^1.2.2
  local_auth: ^2.3.0
  logger: ^2.5.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
